---
- debug:
    msg: "Creating new branch {{ branch_item }}"

- name: Create | Create DB
  become: yes
  mysql_db:
    name: "{{ item.name }}_{{ branch_item }}"
    state: present
    encoding: "utf8"
    collation: "utf8_general_ci"
  with_items: "{{ buildbranches.databases }}"

- name: Create | Import DB SQL file
  become: yes
  mysql_db:
    name: "{{ item.name }}_{{ branch_item }}"
    state: import
    target: "{{ item.target }}"
  with_items: "{{ buildbranches.databases }}"
  async: 3600
  poll: 0

- name: Create | Create site branch directory
  file:
    path: "{{ buildbranches.build_dir }}/{{ branch_item }}"
    state: directory

- name: Create | Copy site files
  shell: "rsync -aAX --inplace {% for path in buildbranches.sync_exclude %}--exclude '{{ path }}' {% endfor %}master/ {{ branch_item }}/"
  args:
    chdir: "{{ buildbranches.build_dir }}"

- name: Create | Ensure custom settings are present
  copy:
    content: "{{ item.value | regex_replace('REPLACEBRANCH', branch_item) }}"
    dest: "{{ buildbranches.build_dir }}/{{ branch_item }}/{{ item.dest }}"
    follow: yes
  with_items: "{{ buildbranches.configs }}"
  tags: config

- name: Replace settings
  replace:
    path: "{{ buildbranches.build_dir }}/{{ branch_item }}/{{ item.file }}"
    regexp: "{{ item.regex }}"
    replace: '\1{{ branch_item }}\2'
  with_items: "{{ buildbranches.replace | default([]) }}"
  tags: config
  
- name: Create | Run update tasks
  include: update.yml
  vars:
    update_branch_item: "{{ branch_item }}"

- name: Get Changelog
  shell: "git log master..origin/{{ branch_item }} --pretty=format:\"%h %an, %ar: %s\" --no-merges"
  args:
    chdir: "{{ buildbranches.build_dir }}/{{ branch_item }}"
  register: changelog
  ignore_errors: yes

- name: Send notification to Slack
  slack:
    token: "{{ buildbranches.slack.token }}"
    msg: "{{ buildbranches.slack.message }}"
    attachments:
      - title: "New Branch site created"
        text: "{{ buildbranches.slack.description }}"
        color: good
        fields:
          - title: "Branch"
            value: "{{ branch_item }}"
            short: "true"
          - title: "URLs"
            value: "http://{{ branch_item }}.{{ buildbranches.domain }}, https://{{ branch_item }}.{{ buildbranches.domain }}"
            short: "true"
          - title: "Branch diff URL"
            value: "{{ buildbranches.diff_url }}/{{ buildbranches.default_branch }}...{{ branch_item }}"
            short: "true"
          - title: "Changelog:"
            value: "{{ changelog.stdout }}"
            short: false
    username: "{{ buildbranches.slack.username }}"
    channel: "{{ buildbranches.slack.channel }}"
    icon_emoji: "{{ buildbranches.slack.icon_emoji }}"
  when: buildbranches.slack.token is defined
