---
- debug:
    msg: "deleting branch {{ branch_item }}"

- name: Delete | Delete site branch
  file:
    path: "{{ buildbranches.build_dir }}/{{ branch_item }}"
    state: absent
  async: 3600
  poll: 0

- name: Delete | Delete DB
  become: yes
  mysql_db:
    name: "{{ item.name }}_{{ branch_item }}"
    state: absent
  with_items: "{{ buildbranches.databases }}"
  async: 3600
  poll: 0
