---
- name: Delete | set branch name
  set_fact: branch="{{ item }}"

- name: Delete | Delete site branch
  file:
    path: "{{ buildbranches.build_dir }}/{{ branch }}"
    state: absent
  async: 3600
  poll: 0  

- name: Delete | Delete DB
  become: yes
  mysql_db:
    name: "{{ buildbranches.db.name }}_{{ branch }}"
    state: absent
  when: buildbranches.db.name
  async: 3600
  poll: 0  
