---
- name: "Get updated branches"
  shell: 'git fetch origin --no-tags --prune 2>&1 >/dev/null | grep "\s\->\sorigin\/" | grep "\.\." | grep -v "{{ buildbranches.exclude_pattern }}" | cut -d"/" -f2'
  args:
    chdir: "{{ buildbranches.build_dir }}/{{ buildbranches.default_branch }}"
  register: updatedbranches
  changed_when: False

- name: Get list of branches
  shell: "echo '{{ buildbranches.default_branch }}' && git branch -r --list --no-merged | grep -v 'HEAD' | grep -v '{{ buildbranches.exclude_pattern }}' | cut -d'/' -f2"
  args:
    chdir: "{{ buildbranches.build_dir }}/{{ buildbranches.default_branch }}"
  register: branches
  changed_when: False

- name: Get list of sites installed
  shell: "find . -maxdepth 1 -mindepth 1 -printf '%f\n'"
  args:
    chdir: "{{ buildbranches.build_dir }}"
  register: sites
  changed_when: False

- name: "Create new branches"
  include: create.yml
  with_items: "{{ branches.stdout_lines | difference(sites.stdout_lines) }}"

- name: "Update branches"
  include: update.yml
  with_items: "{{ updatedbranches.stdout_lines }}"

- name: "Delete branches"
  include: delete.yml
  with_items: "{{ sites.stdout_lines | difference(branches.stdout_lines) }}"

- name: Update VirtualHost
  become: yes
  template:
    src: branches.conf.j2
    dest: "/etc/apache2/sites-available/{{ buildbranches.app }}-branches.conf"
  notify: reload apache

- name: Send notification to Slack
  slack:
    token: "{{ buildbranches.slack.token }}"
    msg: "{{ buildbranches.slack.message }}"
    attachments:
      - title: "New Branch site created"
        text: "{{ buildbranches.slack.description }}"
        color: good
        fields:
          - title: "Branch"
            value: "{{ item }}"
            short: "true"
          - title: "URLs"
            value: "http://{{ item }}.{{ buildbranches.domain }}, https://{{ item }}.{{ buildbranches.domain }}"
            short: "true"
          - title: "Branch diff URL"
            value: "{{ buildbranches.diff_url }}/{{ buildbranches.default_branch }}...{{ item }}"
            short: "true"
    username: "{{ buildbranches.slack.username }}"
    channel: "{{ buildbranches.slack.channel }}"
    icon_emoji: "{{ buildbranches.slack.icon_emoji }}"
  with_items: "{{ branches.stdout_lines | difference(sites.stdout_lines) }}"
  when: buildbranches.slack.token is defined
