- debug: var=buildbranches verbosity=1
  tags: vars

- name: "Get updated branches"
  shell: 'git fetch origin --no-tags --prune 2>&1 >/dev/null | grep "\s\->\sorigin\/" | grep "\.\." | grep -v "{{ buildbranches.exclude_pattern }}" | cut -d"/" -f2'
  args:
    chdir: "{{ buildbranches.build_dir }}/{{ buildbranches.default_branch }}"
  register: updatedbranches

- name: Get list of branches
  shell: "echo '{{ buildbranches.default_branch }}' && git branch -r --list --no-merged | grep -v 'HEAD' | grep -v '{{ buildbranches.exclude_pattern }}' | cut -d'/' -f2"
  args:
    chdir: "{{ buildbranches.build_dir }}/{{ buildbranches.default_branch }}"
  register: branches

- name: Get list of sites installed locally
  shell: "find . -maxdepth 1 -mindepth 1 -printf '%f\n'"
  args:
    chdir: "{{ buildbranches.build_dir }}"
  register: sites

- debug: var=sites verbosity=1
  tags: vars

- debug: var=branches verbosity=1
  tags: vars

- name: "Create new branches"
  include_tasks: create.yml
  with_items: "{{ branches.stdout_lines | difference(sites.stdout_lines) | default([]) }}"
  loop_control:
    loop_var: branch_item

- name: "Update branches"
  include_tasks: update.yml
  with_items: "{{ updatedbranches.stdout_lines | default([]) }}"
  loop_control:
    loop_var: update_branch_item

- name: "Delete branches"
  include_tasks: delete.yml
  with_items: "{{ sites.stdout_lines | difference(branches.stdout_lines) | default([]) }}"
  loop_control:
    loop_var: branch_item

- name: Update VirtualHost
  become: yes
  template:
    src: branches.conf.j2
    dest: "/etc/apache2/sites-available/{{ buildbranches.app }}-branches.conf"
  notify: reload server

- name: Post tasks
  become: yes
  shell: "{{ item }}"
  with_items: "{{ buildbranches.post_tasks | default([]) }}"
