---
- name: Update | set branch name
  set_fact:
    branch: "{{ branch_item }}"

- debug:
    msg: "Updating branch {{ branch }}"

- name: Update | Get branch code
  git:
    dest: "{{ buildbranches.build_dir }}/{{ branch }}"
    force: yes
    repo: "{{ buildbranches.repo }}"
    version: "{{ branch }}"

- name: Update | Run build commands
  shell: "{{ item }}"
  args:
    chdir: "{{ buildbranches.build_dir }}/{{ branch }}"
  with_items: "{{ buildbranches.commands }}"
  async: 3600
  poll: 0
