- name: Setting sitename
  set_fact:
    sitename: "{{ update_branch_item | truncate(buildbranches.truncate_branch, True, '') }}"

- debug:
    msg: "Updating branch {{ sitename }}"

- name: Update | Get branch code
  git:
    dest: "{{ buildbranches.build_dir }}/{{ sitename }}"
    force: yes
    repo: "{{ buildbranches.repo }}"
    version: "{{ update_branch_item }}"

- name: Update | Run build commands
  shell: "{{ item }}"
  environment: "{{ buildbranches.env_vars | default({}) }}"
  args:
    chdir: "{{ buildbranches.build_dir }}/{{ sitename }}"
  with_items: "{{ buildbranches.commands }}"
