---
- debug:
    msg: "Updating branch {{ update_branch_item }}"

- name: Update | Get branch code
  git:
    dest: "{{ buildbranches.build_dir }}/{{ update_branch_item }}"
    force: yes
    repo: "{{ buildbranches.repo }}"
    version: "{{ update_branch_item }}"

- name: Update | Run build commands
  shell: "{{ item }}"
  environment: "{{ buildbranches.env_vars | default({}) }}"  
  args:
    chdir: "{{ buildbranches.build_dir }}/{{ update_branch_item }}"
  with_items: "{{ buildbranches.commands }}"
  async: 3600
  poll: 0
